/*******************************************************************************

  Project: DoPE

  (C) DOLI Elektronik GmbH, 1997-present

Description :
=============

   Header for DOLI PC-EDC interface for Windows

*******************************************************************************/


#ifndef DoPE_INCLUDED
#define DoPE_INCLUDED

//------------------------------------------------------------------------------

#if !defined SUB
  #include  <windows.h>
#endif
#include  <DoPEgeneral.H>
#include  <DoPEcheck.H>
#include  <DoPEcmc.H>
#include  <DoPEcombined.H>
#include  <DoPEcorr.H>
#include  <DoPEctrl.H>
#include  <DoPEdata.H>
#include  <DoPEdebug.H>
#include  <DoPEdisplay.H>
#include  <DoPEeh.H>
#include  <DoPEexpert.H>
#include  <DoPEilc.H>
#include  <DoPEinfo.H>
#include  <DoPEio.H>
#include  <DoPEiosignal.H>
#include  <DoPEkey.H>
#include  <DoPEmove.H>
#include  <DoPEopen.H>
#include  <DoPEoutput.H>
#include  <DoPEsersen.H>
#include  <DoPEsetup.H>
#include  <DoPErmc.H>
#include  <DoPEshield.H>
#include  <DoPEsyn.H>
#include  <DoPEtare.H>

#endif
